apiVersion: v1
kind: Pod
metadata:
  name: pod-mysql
spec:
  containers:
  - image: mysql:5.6
    name: cont-mysql
    env:
      # Use secret in prod use cases
    - name: MYSQL_ROOT_PASSWORD
      value: password
    ports:
    - containerPort: 3306
      name: mysql
    volumeMounts:
    - name: mysql-persistent-storage
      mountPath: /var/lib/mysql
  volumes:
  - name: mysql-persistent-storage
    persistentVolumeClaim:
      claimName: mysql-pv-data