apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
      app: webservice1
spec:
  type: NodePort
  selector:
    app: pod-nginx
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80